/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rover12421.android.godmodel.hash.plugin

import com.android.build.gradle.AppExtension
import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class HashPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        val appExtension = project.extensions.findByType(AppExtension::class.java) ?: return
        appExtension.registerTransform(HashAnnotationTransform(project))
    }
}
